# Generated by Django 6.0 on 2025-12-05 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WaterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('fauna', models.BooleanField(default=True)),
                ('passport_date', models.DateField()),
                ('technical_condition', models.IntegerField(default=0)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pdf', models.FileField(upload_to='passports/')),
                ('priority', models.IntegerField(default=0)),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atla.resourcetype')),
                ('water_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atla.watertype')),
            ],
        ),
    ]
