# Generated by Django 6.0 on 2025-12-06 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atla', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='object',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='PriorityScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('level', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='low', max_length=10)),
                ('formula_version', models.CharField(default='v1', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('obj', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='priority_score', to='Atla.object')),
            ],
        ),
        migrations.AlterField(
            model_name='object',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Atla.region'),
        ),
    ]
