# Generated by Django 6.0 on 2025-12-06 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Atla', '0002_region_object_created_at_priorityscore_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
        migrations.AlterField(
            model_name='object',
            name='water_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Atla.watertype'),
        ),
    ]
